# AutoStop ห้ามแก้ไขอะไรทั้งนั้นในนี้ไม่งั้นโดนแบนนะคับ
# How long (in seconds) should the server wait after starting if no players connect?
startDelay: 300
# How long (in seconds) should the server wait after the last player disconnects?
disconnectDelay: 600
